spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:7847
        namespace: 877bab8f-8daf-4959-b684-8fb3088ef049
        group: SPT_GROUP
      discovery:
        server-addr: 127.0.0.1:7847
        namespace: 877bab8f-8daf-4959-b684-8fb3088ef049
        group: BAMBOO_GROUP
    sentinel:
      transport:
        port: 8721 # 默认8719(当前服务，对sentinel提供的，调用端口号，用于监控服务访问数据)
        dashboard: localhost:9100
      enabled: true # 服务启动时直接建立心跳连接

    stream:
      function:
        definition: generalConsumer;seqConsumer;delayConsumer
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
#          exampleProducer-out-0:
#            producer:
#              group: default-producer
          generalConsumer-in-0:
            consumer:
              # 消息模型：集群-CLUSTERING；广播-BROADCASTING
              messageModel: CLUSTERING
          seqConsumer-in-0:
            consumer:
              messageModel: CLUSTERING
          delayConsumer-in-0:
            consumer:
              messageModel: CLUSTERING
      bindings:
#        # 新版本固定格式：函数名-{out/in}-{index}
#        exampleProducer-out-0:
#          destination: example-general-topic
#          content-type: application/json
        # 定义name为demoConsumer-in-0的binding
        generalConsumer-in-0:
          destination: example-general-topic
          content-type: application/json
          group: general-consumer
        seqConsumer-in-0:
          destination: example-seq-topic
          group: seq-consumer
        delayConsumer-in-0:
          destination: example-delay-topic
          group: delay-consumer

  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
      - optional:nacos:common-config.properties
seata:
  enabled: false
  application-id: ${spring.application.name}
#  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:7847
      namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
      group: SEATA_GROUP
      data-id: seata-server.properties
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      cluster: default
      application: seata-server
      server-addr: 127.0.0.1:7847
      group: SEATA_GROUP
      namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7

logging:
  level:
    org.panda.support: debug
