spring:
  cloud:
    nacos:
      config:
        server-addr: 198.19.249.35:7847
        namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
        group: SPT_GROUP
      discovery:
        server-addr: 198.19.249.35:7847
        namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
        group: BAMBOO_GROUP
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
      - optional:nacos:common-config.properties

seata:
  enabled: true
  application-id: ${spring.application.name}
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:7847
      namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
      group: SEATA_GROUP
      data-id: seata-server.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:7847
      group: SEATA_GROUP
      namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
