spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:7847
        namespace: 877bab8f-8daf-4959-b684-8fb3088ef049
        group: SPT_GROUP
      discovery:
        server-addr: 127.0.0.1:7847
        namespace: 877bab8f-8daf-4959-b684-8fb3088ef049
        group: BAMBOO_GROUP
    sentinel:
      transport:
        port: 8721 # 默认8719(当前服务，对sentinel提供的，调用端口号，用于监控服务访问数据)
        dashboard: localhost:9100
      enabled: true # 服务启动时直接建立心跳连接
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=true
      - optional:nacos:common-config.properties

seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:7847
      namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
      group: SEATA_GROUP
      data-id: seata-server.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:7847
      group: SEATA_GROUP
      namespace: f2b00b45-b5a5-46e4-a2ad-67e83b2058b7
      username: "nacos"
      password: "nacos"
