spring:
  application:
    name: ms-auth
  profiles:
    active: dev
server:
  port: 11005
  servlet:
    context-path: /cas

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.panda.ms.auth: debug
