server:
  port: 12001
spring:
  application:
    name: gateway-cloud-service
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
