spring:
  application:
    name: spt-gateway
  profiles:
    active: demo
  main:
    web-application-type: reactive
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
server:
  port: 12001
