spring:
  cloud:
    nacos:
      discovery:
        server-addr: bamboo-cloud-spt01.orb.local:8848
        namespace: 9c6ca821-85b7-4b4f-8d95-6be72ef1505b
        group: SPT_GROUP
      config:
        server-addr: bamboo-cloud-spt01.orb.local:8848
        namespace: 9c6ca821-85b7-4b4f-8d95-6be72ef1505b
        group: SPT_GROUP
        file-extension: yml
#  config:
#    import:
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
