spring:
  cloud:
    nacos:
      discovery:
        group: BAMBOO_GROUP
    gateway:
      # 网关路由配置
      routes:
        - id: document_route
          # lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略
          uri: lb://ms-document
          # 断言规则，用于路由规则的匹配
          predicates:
            - Path=/ms-document/**
          filters:
            # 转发之前，去掉第一层的路径
            - StripPrefix=1
        - id: ms-notice_route
          uri: lb://ms-notice
          predicates:
            - Path=/ms-notice/**
          filters:
            - StripPrefix=1
        - id: payment_route
          uri: lb://ms-payment
          predicates:
            - Path=/ms-payment/**
          filters:
            - StripPrefix=1
      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
