spring:
  cloud:
    nacos:
      config:
        server-addr: bamboo-cloud-spt01.orb.local:8848
        namespace: 42f07098-2a70-4a75-9f09-361ed9f9b5ca
        group: SPT_GROUP
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=false
      - optional:nacos:common-config.properties?refreshEnabled=true
