spring:
  cloud:
    nacos:
      config:
        server-addr: bamboo-cloud-spt01.orb.local:8848
        namespace: ff4084cf-205e-41a3-a3a7-7b2dd7008427
        group: SPT_GROUP
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml?refreshEnabled=false
      - optional:nacos:common-config.properties?refreshEnabled=true
