spring:
  application:
    name: ms-notice
  profiles:
    active: dev
  messages:
    basename: message/error/notice-error,message/info/notice-info
server:
  port: 11002

logging:
  level:
    org.panda.ms.notice: debug
